PROJECT_ID = 'project-name'
FIRESTORE_PROJECT_ID = ''
FIRESTORE_COLLECTION_NAME = ''
JOB_NAME = ''
SUBSCRIPTION_ID = 'subscription-name'
TOPIC_NAME = 'smartpipenet-sensor-data'
MQTT_BROKER_URL = ''
MQTT_TOPIC = ''
CASSANDRA_HOSTS = 'localhost'
CASSANDRA_KEYSPACE = 'power_plants'
CASSANDRA_TABLE = 'iot_sensor'
INSTANCE_ID = ''
TABLE_ID = ''
DATASET_ID = ''
COLUMN_FAMILY_ID = ''

NUM_WORKERS = 8
